# Unbind default prefix (Ctrl+b)
unbind C-b

# Set new prefix to Ctrl+s
set-option -g prefix C-s

# Bind Ctrl+s to send the prefix
bind-key C-s send-prefix

# automatically close gaps in numbering
set -g renumber-windows on

# repeatable window navigation
bind -r h previous-window
bind -r l next-window
